baseURL = 'https://anrbn.gitlab.io/'
title = "Your Blog Title"
theme = "temple"
# If not set, it will not appear. Otherwise it will show below your footer links
copyright = "(c) 2008 - 2014"

# Enables Chroma-based syntax highlighting with theme "friendly"
# See https://xyproto.github.io/splash/docs/ for other theme options
pygmentsStyle = "friendly"
# If true, Chroma will highlight GitHub-style code fences in addition to
# highlight shortcodes
pygmentsCodeFences = true

[params]
  # Enables the topmenu, which pulls from categories
  topmenu = "categories"

  # Enables custom date format (optional, the default is MM-DD-YYYY)
  # For reference to date and time templating, see:
  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateformatpretty = "2006-01-02"

  # Enables dark mode
  # Note that your syntax highlighting should be changed accordingly. If you
  # choose a syntax-highlighting with a white-background it won't appear
  # correctly. See https://github.com/aos/temple/pull/35
  darkmode = true

  # Enable table of contents, this can be overridden by page level parameter `toc`.
  toc = true

  # Location of favicon.ico in the "static/" directory
  favicon_location = "favicon.ico" # This assumes it's in static/favicon.ico

# Builds a list page for each category given
[taxonomies]
  tag = "tags"
  category = "categories"

[author]
  name = "Aos Dabbagh"
  github = "aos"
  email = "your@email.com"
  # Note: GA Javascript snippet is not included if "gaid" is left blank
  gaid = "Your Google Analytics ID"
  twitter = "twitterID"
  medium = "mediumUsername"